### ISSUE TITLE
Issues using the proxy

### ISSUE THREAD

**Issue by paolosalvatori** [gsoft-inc/azure-cli-credentials-proxy#38]
**Describe the bug**
My containerized Python application gets the following error:

```text
Attempted credentials:
2024-05-31 10:40:01     EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
2024-05-31 10:40:01 Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
2024-05-31 10:40:01     ManagedIdentityCredential: invalid literal for int() with base 10: '2024-05-31T09:49:50.0000000+00:00'
2024-05-31 10:40:01 To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
2024-05-31 10:40:01 2024-05-31 08:40:01 - DefaultAzureCredential failed to retrieve a token from the included credentials.
2024-05-31 10:40:01 Attempted credentials:
2024-05-31 10:40:01     EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
2024-05-31 10:40:01 Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
2024-05-31 10:40:01     ManagedIdentityCredential: invalid literal for int() with base 10: '2024-05-31T09:49:50.0000000+00:00'
2024-05-31 10:40:01 To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
```

**To Reproduce**

I created the following `docker-compose.yml` to start the Azure CLI credentials proxy and my Docker container:

```yaml
services:
  azclicredsproxy:
    image: workleap/azure-cli-credentials-proxy:latest
    volumes:
      - "/home/paolos/.azure:/app/.azure/"

  chat:
    depends_on:
      - azclicredsproxy
    image: chainlitchat:v1
    environment:
      - AZURE_OPENAI_BASE=https://paolosopenai.openai.azure.com/
      - AZURE_OPENAI_MODEL=gpt-35-turbo-16k
      - AZURE_OPENAI_DEPLOYMENT=gpt-35-turbo-16k
      - AZURE_OPENAI_API_VERSION=2024-02-15-preview
      - AZURE_OPENAI_TYPE=azure_ad
      - TEMPERATURE=0.9
      - IDENTITY_ENDPOINT=http://azclicredsproxy:8080/token
      - IMDS_ENDPOINT=random-placeholder
    ports:
      - "8000:8000"  
```

When I run the `docker-compose up --detach`, both containers start as expected. My `chat` app uses the following code to authenticate against Azure OpenAI:

```python
# Create Token Provider
token_provider = get_bearer_token_provider(
    DefaultAzureCredential(), "https://cognitiveservices.azure.com/.default"
)

# Configure OpenAI
openai = AsyncAzureOpenAI(
      api_version=api_version,
      azure_endpoint=api_base,
      azure_ad_token_provider=token_provider,
      max_retries=max_retries,
      timeout=timeout,
 )
```

If I look at the log of the `azclicredsproxy` container, I can see that the proxy call succeeds:

```text
2024-05-31 10:38:55 08:38:55 info: Microsoft.Hosting.Lifetime[14] Now listening on: http://[::]:8080
2024-05-31 10:38:55 08:38:55 info: Microsoft.Hosting.Lifetime[0] Application started. Press Ctrl+C to shut down.
2024-05-31 10:38:55 08:38:55 info: Microsoft.Hosting.Lifetime[0] Hosting environment: Production
2024-05-31 10:38:55 08:38:55 info: Microsoft.Hosting.Lifetime[0] Content root path: /app
2024-05-31 10:40:00 08:40:00 info: Microsoft.AspNetCore.Hosting.Diagnostics[1] Request starting HTTP/1.1 GET http://azclicredsproxy:8080/token?api-version=2019-11-01&resource=https://cognitiveservices.azure.com - -
2024-05-31 10:40:00 08:40:00 info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0] Executing endpoint 'HTTP: GET /token'
2024-05-31 10:40:01 08:40:01 info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1] Executed endpoint 'HTTP: GET /token'
2024-05-31 10:40:01 08:40:01 info: Microsoft.AspNetCore.Hosting.Diagnostics[2] Request finished HTTP/1.1 GET http://azclicredsproxy:8080/token?api-version=2019-11-01&resource=https://cognitiveservices.azure.com - - - 200 - application/json;+charset=utf-8 735.7467ms
```

However, the `chat` application fails with the following error:

```text
Attempted credentials:
2024-05-31 10:40:01     EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
2024-05-31 10:40:01 Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
2024-05-31 10:40:01     ManagedIdentityCredential: invalid literal for int() with base 10: '2024-05-31T09:49:50.0000000+00:00'
2024-05-31 10:40:01 To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
2024-05-31 10:40:01 2024-05-31 08:40:01 - DefaultAzureCredential failed to retrieve a token from the included credentials.
2024-05-31 10:40:01 Attempted credentials:
2024-05-31 10:40:01     EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
2024-05-31 10:40:01 Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
2024-05-31 10:40:01     ManagedIdentityCredential: invalid literal for int() with base 10: '2024-05-31T09:49:50.0000000+00:00'
2024-05-31 10:40:01 To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
```

If I run the following command inside the proxy container:

```bash
wget --no-check-certificate -qO- "http://azclicredsproxy:8080/token?api-version=2019-11-01&resource=https://cognitiveservices.azure.com" > output.txt
```

The call successfully completes and returns a valid JWT, but there might be a problem with the `expires_on` format:

- The `expires_on` returned by the proxy has the following format `2024-05-31T15:34:45.0000000+00:00` 
- The `expires_on` returned by an `az account get-access-token` is a number, e.g. `1717170534` in epoch format.

I changed the `Program.cs` as follows:

```C#
using System.Globalization;
using Azure.Core;
using Azure.Identity;

var tokenCredential = new AzureCliCredential();
var app = WebApplication.CreateBuilder(args).Build();

// Can be consumed by ManagedIdentityCredential by specifying IDENTITY_ENDPOINT and IMDS_ENDPOINT environment variables to this action URL
// See https://github.com/Azure/azure-sdk-for-net/blob/Azure.Identity_1.8.0/sdk/identity/Azure.Identity/src/AzureArcManagedIdentitySource.cs
app.MapGet("/token", async (string resource) =>
{
    var token = await tokenCredential.GetTokenAsync(new TokenRequestContext(new[] { resource }));
    return new Dictionary<string, string> { ["access_token"] = token.Token, ["expiresOn"] = token.ExpiresOn.ToString("O", CultureInfo.InvariantCulture), ["expires_on"] = token.ExpiresOn.ToUnixTimeSeconds().ToString() };
});

app.Run();
```

Now, I get another exception:

```text
2024-05-31 15:20:42 - DefaultAzureCredential failed to retrieve a token from the included credentials.
2024-05-31 17:20:42 Attempted credentials:
2024-05-31 17:20:42     EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
2024-05-31 17:20:42 Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
2024-05-31 17:20:42     ManagedIdentityCredential: 'resource'
2024-05-31 17:20:42 To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
2024-05-31 17:20:42 2024-05-31 15:20:42 - DefaultAzureCredential failed to retrieve a token from the included credentials.
2024-05-31 17:20:42 Attempted credentials:
2024-05-31 17:20:42     EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
2024-05-31 17:20:42 Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
2024-05-31 17:20:42     ManagedIdentityCredential: 'resource'
2024-05-31 17:20:42 To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
2024-05-31 17:20:42 Traceback (most recent call last):
2024-05-31 17:20:42   File "/opt/venv/lib/python3.11/site-packages/chainlit/utils.py", line 39, in wrapper
2024-05-31 17:20:42     return await user_function(**params_values)
2024-05-31 17:20:42            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31 17:20:42   File "/app/chat.py", line 90, in on_message
2024-05-31 17:20:42     async for stream_resp in await openai.chat.completions.create(
2024-05-31 17:20:42                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31 17:20:42   File "/opt/venv/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1211, in create
2024-05-31 17:20:42     return await self._post(
2024-05-31 17:20:42            ^^^^^^^^^^^^^^^^^
2024-05-31 17:20:42   File "/opt/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1536, in post
2024-05-31 17:20:42     return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
2024-05-31 17:20:42            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31 17:20:42   File "/opt/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1315, in request
2024-05-31 17:20:42     return await self._request(
2024-05-31 17:20:42            ^^^^^^^^^^^^^^^^^^^^
2024-05-31 17:20:42   File "/opt/venv/lib/python3.11/site-packages/openai/_base_client.py", line 1332, in _request
2024-05-31 17:20:42     await self._prepare_options(options)
2024-05-31 17:20:42   File "/opt/venv/lib/python3.11/site-packages/openai/lib/azure.py", line 517, in _prepare_options
2024-05-31 17:20:42     azure_ad_token = await self._get_azure_ad_token()
2024-05-31 17:20:42                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31 17:20:42   File "/opt/venv/lib/python3.11/site-packages/openai/lib/azure.py", line 501, in _get_azure_ad_token
2024-05-31 17:20:42     token = provider()
2024-05-31 17:20:42             ^^^^^^^^^^
2024-05-31 17:20:42   File "/opt/venv/lib/python3.11/site-packages/azure/identity/_bearer_token_provider.py", line 43, in wrapper
2024-05-31 17:20:42     policy.on_request(request)
2024-05-31 17:20:42   File "/opt/venv/lib/python3.11/site-packages/azure/core/pipeline/policies/_authentication.py", line 99, in on_request
2024-05-31 17:20:42     self._token = self._credential.get_token(*self._scopes)
2024-05-31 17:20:42                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31 17:20:42   File "/opt/venv/lib/python3.11/site-packages/azure/identity/_credentials/default.py", line 225, in get_token
2024-05-31 17:20:42     token = super().get_token(*scopes, claims=claims, tenant_id=tenant_id, **kwargs)
2024-05-31 17:20:42             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-31 17:20:42   File "/opt/venv/lib/python3.11/site-packages/azure/identity/_credentials/chained.py", line 124, in get_token
2024-05-31 17:20:42     raise ClientAuthenticationError(message=message)
2024-05-31 17:20:42 azure.core.exceptions.ClientAuthenticationError: DefaultAzureCredential failed to retrieve a token from the included credentials.
2024-05-31 17:20:42 Attempted credentials:
2024-05-31 17:20:42     EnvironmentCredential: EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
2024-05-31 17:20:42 Visit https://aka.ms/azsdk/python/identity/environmentcredential/troubleshoot to troubleshoot this issue.
2024-05-31 17:20:42     ManagedIdentityCredential: 'resource'
2024-05-31 17:20:42 To mitigate this issue, please refer to the troubleshooting guidelines here at https://aka.ms/azsdk/python/identity/defaultazurecredential/troubleshoot.
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: WSL2 on Windows 11
 - Version: 11
 - IDE: Visual Studio Code

**Comment by meziantou** [comment]
closed by https://github.com/gsoft-inc/azure-cli-credentials-proxy/pull/41
